version: "3"

services:
  nextjs:
    build: ./
    environment:
      - DB_NAME=fd
      - MONGO_URL=mongodb://admin:aserty1234@194.67.67.180:27017/?authMechanism=DEFAULT
  nginx: 
    build: ./nginx
    ports:
      - 80:80    
